[package]
name = "tinyray"
version.workspace = true
edition.workspace = true

[dependencies]
tinyray-core = { path = "../tinyray-core" }
tinyray-proto = { path = "../tinyray-proto" }
tinyray-membership = { path = "../tinyray-membership" }
serde.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true
rmp-serde.workspace = true
rmp.workspace = true
rmpv.workspace = true
tokio.workspace = true
async-trait.workspace = true
sha2.workspace = true
fastrand = "2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
tinyray-registry = { path = "../tinyray-registry" }
