[package]
name = "tinyray-client"
version.workspace = true
edition.workspace = true

[lib]
name = "_tinyray"
crate-type = ["cdylib", "rlib"]

[dependencies]
tinyray-proto = { path = "../tinyray-proto" }
tinyray-registry = { path = "../tinyray-registry" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
hyper.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true
bytes.workspace = true
pyo3 = { version = "0.22", features = ["extension-module"] }
